apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: quickstarts-bonfire-tekton
  namespace: console-platex-services-tenant
spec:
  application: quickstarts
  params:
  - name: APP_NAME
    value: quickstarts
  - name: COMPONENTS
    value: quickstarts
  - name: COMPONENT_NAME
    value: quickstarts
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsights/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
