apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: olm-operator
  namespace: konflux-samples-tenant
  annotations:
    # This stub annotation is needed until KFLUXBUGS-1300 is resolved.
    hello: world
spec:
  displayName: olm-operator
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: gatekeeper
  namespace: konflux-samples-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    # If building an FBC component, replace the above line with the one below
    # build.appstudio.openshift.io/pipeline: '{"name":"fbc-builder","bundle":"latest"}'
spec:
  application: olm-operator
  componentName: gatekeeper
  build-nudges-ref:
    - gatekeeper-operator-bundle
  source:
    git:
      revision: main
      url: https://github.com/konflux-ci/olm-operator-konflux-sample
      dockerfileUrl: Containerfile.gatekeeper
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: gatekeeper-operator
  namespace: konflux-samples-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    # If building an FBC component, replace the above line with the one below
    # build.appstudio.openshift.io/pipeline: '{"name":"fbc-builder","bundle":"latest"}'
spec:
  application: olm-operator
  componentName: gatekeeper-operator
  build-nudges-ref:
    - gatekeeper-operator-bundle
  source:
    git:
      revision: main
      url: https://github.com/konflux-ci/olm-operator-konflux-sample
      dockerfileUrl: Containerfile.gatekeeper-operator
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: gatekeeper-operator-bundle
  namespace: konflux-samples-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    # If building an FBC component, replace the above line with the one below
    # build.appstudio.openshift.io/pipeline: '{"name":"fbc-builder","bundle":"latest"}'
spec:
  application: olm-operator
  componentName: gatekeeper-operator-bundle
  source:
    git:
      revision: main
      url: https://github.com/konflux-ci/olm-operator-konflux-sample
      dockerfileUrl: Containerfile.gatekeeper-operator-bundle
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-olm-operator-gatekeeper
  namespace: konflux-samples-tenant
  labels:
    appstudio.redhat.com/application: olm-operator
    appstudio.redhat.com/component: gatekeeper
spec:
  image:
    name: konflux-samples-tenant/olm-operator/gatekeeper
    visibility: public
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-olm-operator-gatekeeper-operator
  namespace: konflux-samples-tenant
  labels:
    appstudio.redhat.com/application: olm-operator
    appstudio.redhat.com/component: gatekeeper-operator
spec:
  image:
    name: konflux-samples-tenant/olm-operator/gatekeeper-operator
    visibility: public
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-olm-operator-gatekeeper-operator-bundle
  namespace: konflux-samples-tenant
  labels:
    appstudio.redhat.com/application: olm-operator
    appstudio.redhat.com/component: gatekeeper-operator-bundle
spec:
  image:
    name: konflux-samples-tenant/olm-operator/gatekeeper-operator-bundle
    visibility: public
