apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: trustee-enterprise-contract
  namespace: ose-osc-tenant
spec:
  params:
    - name: POLICY_CONFIGURATION
      # It should be possible to use registry-standard when this one is resolved:
      # https://issues.redhat.com/browse/STONEBLD-2618.
      # value: rhtap-releng-tenant/registry-standard
      value: rhtap-releng-tenant/tmp-onboard-policy
  application: trustee
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: "https://github.com/redhat-appstudio/build-definitions"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
